#!/usr/bin/env node

import { readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const appPrefix = join(__dirname, '../');

/** @param {string} dir */
async function generateImports(dir) {
  const importStatements = (await readdir(join(appPrefix, dir)))
    .filter(function component(filename) {
      return filename.endsWith('.js') && !filename.endsWith('.spec.js') && !filename.endsWith('.test.js');
    })
    .map(function renderImport(filename) {
      return `import '#${dir}/${filename}';`;
    })
    .join('\n');
  return `\n${importStatements}`;
}

await writeFile(join(appPrefix, 'web/app.js'), `// Generated by scripts/generate-app.js
${await generateImports('web')}
${await generateImports('web/desktop/components')}
${await generateImports('web/contexts')}
${await generateImports('web/databases')}
${await generateImports('web/directives')}
${await generateImports('web/hooks')}
${await generateImports('web/tools')}
${await generateImports('web/desktop/views')}
`, { encoding: 'utf-8' });
